require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubsController do

  # This should return the minimal set of attributes required to create a valid
  # Sub. As you add validations to Sub, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all subs as @subs" do
      sub = Sub.create! valid_attributes
      get :index, {}, valid_session
      assigns(:subs).should eq([sub])
    end
  end

  describe "GET show" do
    it "assigns the requested sub as @sub" do
      sub = Sub.create! valid_attributes
      get :show, {:id => sub.to_param}, valid_session
      assigns(:sub).should eq(sub)
    end
  end

  describe "GET new" do
    it "assigns a new sub as @sub" do
      get :new, {}, valid_session
      assigns(:sub).should be_a_new(Sub)
    end
  end

  describe "GET edit" do
    it "assigns the requested sub as @sub" do
      sub = Sub.create! valid_attributes
      get :edit, {:id => sub.to_param}, valid_session
      assigns(:sub).should eq(sub)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sub" do
        expect {
          post :create, {:sub => valid_attributes}, valid_session
        }.to change(Sub, :count).by(1)
      end

      it "assigns a newly created sub as @sub" do
        post :create, {:sub => valid_attributes}, valid_session
        assigns(:sub).should be_a(Sub)
        assigns(:sub).should be_persisted
      end

      it "redirects to the created sub" do
        post :create, {:sub => valid_attributes}, valid_session
        response.should redirect_to(Sub.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sub as @sub" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sub.any_instance.stub(:save).and_return(false)
        post :create, {:sub => { "user" => "invalid value" }}, valid_session
        assigns(:sub).should be_a_new(Sub)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sub.any_instance.stub(:save).and_return(false)
        post :create, {:sub => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sub" do
        sub = Sub.create! valid_attributes
        # Assuming there are no other subs in the database, this
        # specifies that the Sub created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sub.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => sub.to_param, :sub => { "user" => "" }}, valid_session
      end

      it "assigns the requested sub as @sub" do
        sub = Sub.create! valid_attributes
        put :update, {:id => sub.to_param, :sub => valid_attributes}, valid_session
        assigns(:sub).should eq(sub)
      end

      it "redirects to the sub" do
        sub = Sub.create! valid_attributes
        put :update, {:id => sub.to_param, :sub => valid_attributes}, valid_session
        response.should redirect_to(sub)
      end
    end

    describe "with invalid params" do
      it "assigns the sub as @sub" do
        sub = Sub.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sub.any_instance.stub(:save).and_return(false)
        put :update, {:id => sub.to_param, :sub => { "user" => "invalid value" }}, valid_session
        assigns(:sub).should eq(sub)
      end

      it "re-renders the 'edit' template" do
        sub = Sub.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sub.any_instance.stub(:save).and_return(false)
        put :update, {:id => sub.to_param, :sub => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sub" do
      sub = Sub.create! valid_attributes
      expect {
        delete :destroy, {:id => sub.to_param}, valid_session
      }.to change(Sub, :count).by(-1)
    end

    it "redirects to the subs list" do
      sub = Sub.create! valid_attributes
      delete :destroy, {:id => sub.to_param}, valid_session
      response.should redirect_to(subs_url)
    end
  end

end
